arm_left:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  # kinematics_solver: motoman_sda10f_arm_left_kinematics/IKFastKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
arm_right:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
arms:
  kinematics_solver: generalik_kinematics_plugin/GeneralIKKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  # kinematics_solver_timeout: 0.1
  kinematics_solver_ik_links:
    - arm_left_link_7_t
    - arm_right_link_7_t
  kinematics_solver_step_size: 0.1
  kinematics_solver_tolerance: 0.002
  max_solver_iterations: 100
  kinematics_solver_check_limits: true